name       : python-debugpy
version    : 1.5.1
release    : 1
source     :
    - https://pypi.io/packages/source/d/debugpy/debugpy-1.5.1.zip : d2b09e91fbd1efa4f4fda121d49af89501beda50c18ed7499712c71a4bf3452e
homepage   : https://github.com/microsoft/debugpy
license    : MIT
component  : programming.python
summary    : A debugger for Python
description: |
    An implementation of the Debug Adapter Protocol for Python.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
