name       : python-debugpy
version    : 1.6.0
release    : 4
source     :
    - https://pypi.io/packages/source/d/debugpy/debugpy-1.6.0.zip : 7b79c40852991f7b6c3ea65845ed0f5f6b731c37f4f9ad9c61e2ab4bd48a9275
homepage   : https://github.com/microsoft/debugpy
license    : MIT
component  : programming.python
summary    : A debugger for Python
description: |
    An implementation of the Debug Adapter Protocol for Python.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
